/*import express framework for routing  and set all api's routes*/
const express = require("express");
const router = express.Router();
const verifyToken = require("../Middlewares/VerifyToken");
const signUpRouter = require("../Controllers/SignUpUser");
const loginRouter = require("../Controllers/LoginUser");
const findUserRouter = require("../Controllers/FindAllUser");
const updateUserRouter = require("../Controllers/UpdateUser");
const deleteUserRouter = require("../Controllers/DeleteUser");
const forgotPasswordRouter = require("../Controllers/ForgotPassword");
const changePasswordRouter = require("../Controllers/ChangePassword");
const uploadImageRouter = require("../Controllers/UplaodImage");
const multer = require("../Middlewares/multer");
const uploadPostRouter = require("../Controllers/UploadPost");
const deletePostRouter = require("../Controllers/DeletePost");
const updatePostRouter = require("../Controllers/UpdatePost");
const addCommentRouter = require("../Controllers/AddComment");
const sendFriendRequestRouter = require("../Controllers/SendFriendRequest");
const acceptFriendReqRouter = require("../Controllers/AcceptFriendReq");
const deleteFriendReqRouter = require("../Controllers/DeleteFriendreq");
const blockMyFriendRouter = require("../Controllers/BlockUser");
const unblockMyFriendRouter = require("../Controllers/UnblockUser");
const likePostRouter = require("../Controllers/LikePost");
const dilikePostRouter = require("../Controllers/DislikePost");

router.post("/signUp", signUpRouter);
router.post("/login", loginRouter);
router.get("/findAllUser", findUserRouter);
router.put("/updateUser", verifyToken, updateUserRouter);
router.delete("/deleteUser", verifyToken, deleteUserRouter);
router.put("/forgotPassword", verifyToken, forgotPasswordRouter);
router.put("/changePassword", verifyToken, changePasswordRouter);
router.post("/uploadImage", multer, uploadImageRouter);
router.post("/uploadPost", verifyToken, uploadPostRouter);
router.delete("/deletePost/:_id", verifyToken, deletePostRouter);
router.put("/updatePost/:_id", verifyToken, updatePostRouter);
router.post("/addComment", verifyToken, addCommentRouter);
router.post("/sendFriendReq/:searchKey", verifyToken, sendFriendRequestRouter);
router.get("/acceptReq", verifyToken, acceptFriendReqRouter);
router.delete("/deleteReq", verifyToken, deleteFriendReqRouter);
router.get("/blockMyFriend", verifyToken, blockMyFriendRouter);
router.post("/unblockUser", verifyToken, unblockMyFriendRouter);
router.post("/addLikes", verifyToken, likePostRouter);
router.post("/addDislike", verifyToken, dilikePostRouter);
/*export this file to index file */
module.exports = router;
